export const EARLY_TERMINATED_STAGE_SLUG = 'EARLY_TERMINATED'
export const EXITED_STAGE_SLUG = 'EXITED'
export const WATCHLIST_STAGE_SLUG = 'WATCHLIST'

export const TERMINAL_STAGE_SLUGS = new Set([
  EARLY_TERMINATED_STAGE_SLUG,
  EXITED_STAGE_SLUG,
  'INVESTED',
  'APPROVED_UNINVESTED',
])
